services:
  - type: web
    name: taolavh10
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taolavh10-db
          property: connectionString
      - key: PUBLIC_API_URL
        value: https://taolavh10.onrender.com
      - key: REQUIRE_POSTGRES
        value: "true"

databases:
  - name: taolavh10-db
    databaseName: taolavh10
    user: taolavh10
